// <auto-generated>
// Generated by tools/gen_2d_colorways.py from the Gamepad-Asset-Pack
// colorway templates. Do not edit by hand: rerun the generator.
// </auto-generated>

using System.Collections.Generic;

namespace PadForge.Models2D
{
    /// <summary>One 2D colorway: the appearance id it answers to
    /// (shared with the 3D model families where the same physical
    /// colorway exists), its display name, its base render, and the
    /// rest-art sprite files that differ from the default's.</summary>
    public sealed class Colorway2D
    {
        public string Id { get; }
        public string Name { get; }
        public string BaseFile { get; }
        public IReadOnlyDictionary<string, string> Overrides { get; }
        public Colorway2D(string id, string name, string baseFile,
            IReadOnlyDictionary<string, string> overrides)
        { Id = id; Name = name; BaseFile = baseFile; Overrides = overrides; }
    }

    /// <summary>2D colorway sets per asset folder. The family key is
    /// the per-pad appearance store's key (PadSetting.Model3DAppearances),
    /// the same one the 3D picker writes, so one selection drives both
    /// views; a view without art for the chosen id falls back to its
    /// default. Entry 0 is the default (the stock files).</summary>
    public static class Controller2DColorways
    {
        private static readonly IReadOnlyDictionary<string, string> None
            = new Dictionary<string, string>();

        private static readonly Colorway2D[] Set_DualSense =
        {
            new("White", "White", "DualSense_base.png",
                None),
            new("Midnight", "Midnight Black", "DualSense_base_Midnight.png",
                None),
            new("CosmicRed", "Cosmic Red", "DualSense_base_CosmicRed.png",
                None),
            new("GalacticPurple", "Galactic Purple", "DualSense_base_GalacticPurple.png",
                None),
            new("NovaPink", "Nova Pink", "DualSense_base_NovaPink.png",
                None),
            new("StarlightBlue", "Starlight Blue", "DualSense_base_StarlightBlue.png",
                None),
        };

        private static readonly Colorway2D[] Set_DS4 =
        {
            new("JetBlack", "Jet Black", "DS4_V2_base.png",
                None),
            new("GlacierWhite", "Glacier White", "DS4_V2_base_GlacierWhite.png",
                new Dictionary<string, string> { { "DS4_V2_LeftAnalogStick.png", "DS4_V2_LeftAnalogStick_GlacierWhite.png" }, { "DS4_V2_RightAnalogStick.png", "DS4_V2_RightAnalogStick_GlacierWhite.png" } }),
            new("Gold", "Gold", "DS4_V2_base_Gold.png",
                new Dictionary<string, string> { { "DS4_V2_LeftAnalogStick.png", "DS4_V2_LeftAnalogStick_Gold.png" }, { "DS4_V2_RightAnalogStick.png", "DS4_V2_RightAnalogStick_Gold.png" } }),
            new("MagmaRed", "Magma Red", "DS4_V2_base_MagmaRed.png",
                None),
            new("MidnightBlue", "Midnight Blue", "DS4_V2_base_MidnightBlue.png",
                None),
        };

        private static readonly Colorway2D[] Set_XBOXSERIES =
        {
            new("Robot", "Robot White", "XBSeries_base.png",
                None),
            new("Carbon", "Carbon Black", "XBSeries_base_Carbon.png",
                new Dictionary<string, string> { { "XBSeries_LeftTrigger.png", "XBSeries_LeftTrigger_Carbon.png" }, { "XBSeries_RightTrigger.png", "XBSeries_RightTrigger_Carbon.png" } }),
            new("ElectricVolt", "Electric Volt", "XBSeries_base_ElectricVolt.png",
                new Dictionary<string, string> { { "XBSeries_LeftStick.png", "XBSeries_LeftStick_ElectricVolt.png" }, { "XBSeries_LeftTrigger.png", "XBSeries_LeftTrigger_Carbon.png" }, { "XBSeries_RightStick.png", "XBSeries_RightStick_ElectricVolt.png" }, { "XBSeries_RightTrigger.png", "XBSeries_RightTrigger_Carbon.png" } }),
            new("ShockBlue", "Shock Blue", "XBSeries_base_ShockBlue.png",
                new Dictionary<string, string> { { "XBSeries_LeftStick.png", "XBSeries_LeftStick_ShockBlue.png" }, { "XBSeries_LeftTrigger.png", "XBSeries_LeftTrigger_Carbon.png" }, { "XBSeries_RightStick.png", "XBSeries_RightStick_ShockBlue.png" }, { "XBSeries_RightTrigger.png", "XBSeries_RightTrigger_Carbon.png" } }),
            new("PulseRed", "Pulse Red", "XBSeries_base_PulseRed.png",
                new Dictionary<string, string> { { "XBSeries_LeftStick.png", "XBSeries_LeftStick_PulseRed.png" }, { "XBSeries_LeftTrigger.png", "XBSeries_LeftTrigger_Carbon.png" }, { "XBSeries_RightStick.png", "XBSeries_RightStick_PulseRed.png" }, { "XBSeries_RightTrigger.png", "XBSeries_RightTrigger_Carbon.png" } }),
            new("DeepPink", "Deep Pink", "XBSeries_base_DeepPink.png",
                new Dictionary<string, string> { { "XBSeries_LeftStick.png", "XBSeries_LeftStick_DeepPink.png" }, { "XBSeries_LeftTrigger.png", "XBSeries_LeftTrigger_Carbon.png" }, { "XBSeries_RightStick.png", "XBSeries_RightStick_DeepPink.png" }, { "XBSeries_RightTrigger.png", "XBSeries_RightTrigger_Carbon.png" } }),
        };

        private static readonly Colorway2D[] Set_XBOXONE =
        {
            new("Robot", "White", "XB1_S_base.png",
                None),
            new("Carbon", "Black", "XB1_S_base_Carbon.png",
                None),
            new("ShockBlue", "Blue", "XB1_S_base_ShockBlue.png",
                new Dictionary<string, string> { { "XB1_LeftStick.png", "XB1_LeftStick_ShockBlue.png" }, { "XB1_LeftTrigger.png", "XB1_LeftTrigger_ShockBlue.png" }, { "XB1_RightStick.png", "XB1_RightStick_ShockBlue.png" }, { "XB1_RightTrigger.png", "XB1_RightTrigger_ShockBlue.png" } }),
            new("PulseRed", "Red", "XB1_S_base_PulseRed.png",
                new Dictionary<string, string> { { "XB1_LeftStick.png", "XB1_LeftStick_PulseRed.png" }, { "XB1_LeftTrigger.png", "XB1_LeftTrigger_PulseRed.png" }, { "XB1_RightStick.png", "XB1_RightStick_PulseRed.png" }, { "XB1_RightTrigger.png", "XB1_RightTrigger_PulseRed.png" } }),
        };

        private static readonly Colorway2D[] Set_XBOX360 =
        {
            new("White", "White", "XB360_base.png",
                None),
            new("Black", "Black", "XB360_base_Black.png",
                new Dictionary<string, string> { { "XB360_LeftStick.png", "XB360_LeftStick_Black.png" }, { "XB360_LeftTrigger.png", "XB360_LeftTrigger_Black.png" }, { "XB360_RightStick.png", "XB360_RightStick_Black.png" }, { "XB360_RightTrigger.png", "XB360_RightTrigger_Black.png" } }),
        };

        private static readonly Colorway2D[] Set_DUALSENSEEDGE =
        {
            new("White", "White", "DualSense_base.png",
                None),
            new("Midnight", "Midnight Black", "DualSense_base_Midnight.png",
                None),
            new("CosmicRed", "Cosmic Red", "DualSense_base_CosmicRed.png",
                None),
            new("GalacticPurple", "Galactic Purple", "DualSense_base_GalacticPurple.png",
                None),
            new("NovaPink", "Nova Pink", "DualSense_base_NovaPink.png",
                None),
            new("StarlightBlue", "Starlight Blue", "DualSense_base_StarlightBlue.png",
                None),
        };

        /// <summary>The colorway set and appearance-store family key
        /// for a 2D asset folder; null set when the folder has no
        /// colorways.</summary>
        public static (string FamilyKey, Colorway2D[] Set) For(string folder) => folder switch
        {
            "DualSense" => ("DualSense", Set_DualSense),
            "DS4" => ("DS4", Set_DS4),
            "XBOXSERIES" => ("XboxSeries", Set_XBOXSERIES),
            "XBOXONE" => ("XboxSeries", Set_XBOXONE),
            "XBOX360" => ("Xbox360", Set_XBOX360),
            "DUALSENSEEDGE" => ("DualSenseEdge", Set_DUALSENSEEDGE),
            _ => (null, null),
        };
    }
}
