// AUTO-GENERATED by tools/gen_mouse_art.py -- do not edit manually.
//
// Layers rendered from Zergatul.Obs.InputOverlay's mouse.svg.
// Copyright (c) 2021 Igor Budzhak. Licensed under the MIT License.
// https://github.com/Zergatul/Zergatul.Obs.InputOverlay
//
// mouse_line.png is the artwork as authored; every other layer is a
// full-canvas alpha mask over it, so the view tints a control without
// redrawing any of the shape. Nothing here approximates a curve.
namespace PadForge.Views;

internal static class MouseArt
{
    internal const double W = 211.6667;
    internal const double H = 296.3333;

    internal const string Dir = "2DModels/MOUSE/";
    internal const string Line = "mouse_line.png";

    internal const string Body = "mouse_body.png";
    internal const string Lmb = "mouse_lmb.png";
    internal const string Rmb = "mouse_rmb.png";
    internal const string Wheel = "mouse_wheel.png";
    internal const string SideUpper = "mouse_sideupper.png";
    internal const string SideLower = "mouse_sidelower.png";

    // Clickable geometry. Never drawn: WPF hit-tests a masked
    // rectangle over its whole rect, not its mask, so each control
    // needs real geometry to answer the mouse.
    /// <summary>41-point hit region.</summary>
    internal const string LmbHit = "M 82.62,8.74 L 79.37,9.24 L 71.14,11.48 L 53.17,18.22 L 48.92,20.72 L 46.18,23.47 L 43.93,27.21 L 42.93,31.46 L 40.69,46.43 L 37.94,72.40 L 36.69,91.87 L 36.94,111.59 L 38.19,116.34 L 40.44,118.58 L 43.18,120.58 L 53.17,126.57 L 73.38,137.56 L 79.87,141.80 L 82.12,144.05 L 83.12,146.04 L 88.61,162.77 L 91.61,169.26 L 94.35,171.51 L 98.35,173.51 L 102.34,174.75 L 105.33,175.00 L 106.08,174.75 L 106.33,173.51 L 106.33,153.28 L 105.83,146.04 L 103.59,143.30 L 99.59,140.55 L 97.35,138.31 L 96.85,137.31 L 93.10,121.08 L 90.11,102.61 L 89.11,93.12 L 88.61,82.13 L 88.11,41.69 L 87.11,12.23 L 86.61,8.99 Z";
    /// <summary>40-point hit region.</summary>
    internal const string RmbHit = "M 135.29,8.99 L 130.54,8.74 L 129.55,9.24 L 129.30,10.49 L 128.30,32.95 L 127.55,84.63 L 126.55,99.11 L 123.56,118.83 L 121.31,129.82 L 119.06,138.06 L 117.32,140.05 L 112.32,143.55 L 111.08,144.80 L 110.33,146.29 L 109.83,155.03 L 109.83,172.51 L 110.08,174.75 L 110.58,175.00 L 114.07,174.75 L 118.56,173.26 L 123.31,170.51 L 124.80,169.01 L 127.80,162.27 L 132.79,146.79 L 134.29,143.80 L 136.04,142.05 L 143.77,137.06 L 162.24,127.07 L 174.48,119.58 L 177.97,116.59 L 179.22,112.09 L 179.72,98.61 L 178.22,71.65 L 174.97,42.19 L 173.23,31.21 L 171.98,26.46 L 168.24,21.47 L 162.99,18.22 L 150.26,13.23 L 140.78,10.24 Z";
    /// <summary>81-point hit region.</summary>
    internal const string WheelHit = "M 103.84,29.46 L 103.59,29.71 L 102.34,29.71 L 102.09,29.96 L 101.34,29.96 L 101.09,30.21 L 100.34,30.21 L 100.09,30.46 L 99.84,30.46 L 99.59,30.71 L 99.09,30.71 L 98.84,30.96 L 98.59,30.96 L 98.10,31.46 L 97.35,31.71 L 95.35,33.70 L 95.35,33.95 L 94.85,34.70 L 94.85,35.20 L 94.60,35.45 L 94.60,81.39 L 94.85,81.64 L 94.85,82.13 L 95.10,82.38 L 95.10,82.63 L 95.60,83.13 L 95.60,83.38 L 96.85,84.63 L 97.10,84.63 L 98.59,85.88 L 98.84,85.88 L 100.09,86.63 L 100.59,86.63 L 100.84,86.88 L 101.34,86.88 L 101.59,87.13 L 102.34,87.13 L 102.59,87.38 L 103.59,87.38 L 103.84,87.63 L 112.57,87.63 L 112.82,87.38 L 114.07,87.38 L 114.32,87.13 L 115.07,87.13 L 115.32,86.88 L 115.82,86.88 L 116.57,86.38 L 117.07,86.38 L 117.32,86.13 L 118.06,85.88 L 118.56,85.38 L 118.81,85.38 L 120.81,83.38 L 120.81,83.13 L 121.56,81.88 L 121.56,55.92 L 119.81,55.92 L 119.31,55.42 L 119.56,55.17 L 119.81,55.17 L 120.06,55.42 L 121.56,55.42 L 121.56,35.45 L 121.31,35.20 L 121.06,34.45 L 120.56,33.95 L 120.56,33.70 L 119.31,32.45 L 119.06,32.45 L 117.56,31.21 L 117.32,31.21 L 116.07,30.46 L 115.57,30.46 L 115.32,30.21 L 114.82,30.21 L 114.57,29.96 L 113.82,29.96 L 113.57,29.71 L 112.32,29.71 L 112.07,29.46 Z";
    /// <summary>72-point hit region.</summary>
    internal const string SideUpperHit = "M 24.96,94.37 L 24.71,94.62 L 23.71,94.62 L 23.21,95.12 L 23.21,95.62 L 22.96,95.87 L 22.96,96.36 L 22.71,96.61 L 22.71,97.36 L 22.46,97.61 L 22.46,98.61 L 22.22,98.86 L 22.22,100.11 L 21.97,100.36 L 21.97,101.86 L 21.72,102.11 L 21.72,103.60 L 21.47,103.85 L 21.47,105.60 L 21.22,105.85 L 21.22,107.85 L 20.97,108.10 L 20.97,110.10 L 20.72,110.34 L 20.72,112.59 L 20.47,112.84 L 20.47,115.34 L 20.22,115.59 L 20.22,118.58 L 19.97,118.83 L 19.97,122.83 L 19.72,123.08 L 19.72,131.32 L 19.97,131.57 L 19.97,132.56 L 20.22,132.81 L 20.22,133.06 L 20.47,133.31 L 20.72,133.31 L 20.97,133.56 L 21.22,133.56 L 21.47,133.81 L 22.46,133.81 L 22.71,134.06 L 24.21,134.06 L 24.46,134.31 L 27.96,134.31 L 27.96,133.81 L 28.21,133.56 L 28.21,126.32 L 28.46,126.07 L 28.46,120.08 L 28.70,119.83 L 28.70,115.34 L 28.95,115.09 L 28.95,111.84 L 29.20,111.59 L 29.20,108.60 L 29.45,108.35 L 29.45,105.85 L 29.70,105.60 L 29.70,103.35 L 29.95,103.11 L 29.95,100.86 L 30.20,100.61 L 30.20,98.36 L 30.45,98.11 L 30.45,94.87 L 29.20,94.87 L 28.95,94.62 L 26.96,94.62 L 26.71,94.37 Z";
    /// <summary>37-point hit region.</summary>
    internal const string SideLowerHit = "M 20.72,137.06 L 20.47,137.31 L 20.22,137.31 L 19.97,137.56 L 19.97,137.81 L 19.72,138.06 L 19.72,139.05 L 19.47,139.30 L 19.47,141.30 L 19.22,141.55 L 19.22,171.26 L 19.47,171.51 L 19.47,173.51 L 19.72,173.76 L 19.72,174.50 L 19.97,174.75 L 19.97,175.25 L 20.22,175.25 L 20.47,175.50 L 20.72,175.50 L 20.97,175.75 L 21.97,175.75 L 22.22,176.00 L 26.96,176.00 L 27.21,175.75 L 27.96,175.75 L 27.96,173.26 L 27.71,173.01 L 27.71,163.02 L 27.46,162.77 L 27.46,159.78 L 27.71,159.53 L 27.71,145.30 L 27.96,145.05 L 27.96,137.31 L 26.71,137.31 L 26.46,137.06 Z";

    /// <summary>The art's own axis of symmetry, measured off the wheel.</summary>
    internal const double CenterX = 108.080;
    internal const double WheelTop = 29.209;
    internal const double WheelBottom = 87.876;
    internal const double BodyTop = 14.230;
    internal const double BodyBottom = 286.847;
}
