// AUTO-GENERATED by tools/gen_mouse_art.py -- do not edit manually.
//
// Layers rendered from Zergatul.Obs.InputOverlay's mouse.svg.
// Copyright (c) 2021 Igor Budzhak. Licensed under the MIT License.
// https://github.com/Zergatul/Zergatul.Obs.InputOverlay
//
// mouse_line.png is the artwork as authored; every other layer is a
// full-canvas alpha mask over it, so the view tints a control without
// redrawing any of the shape. Nothing here approximates a curve.
namespace PadForge.Views;

internal static class MouseArt
{
    internal const double W = 211.6667;
    internal const double H = 296.3333;

    internal const string Dir = "2DModels/MOUSE/";
    internal const string Line = "mouse_line.png";

    internal const string Body = "mouse_body.png";
    internal const string Lmb = "mouse_lmb.png";
    internal const string Rmb = "mouse_rmb.png";
    internal const string Wheel = "mouse_wheel.png";
    internal const string SideUpper = "mouse_sideupper.png";
    internal const string SideLower = "mouse_sidelower.png";

    /// <summary>The art's own axis of symmetry, measured off the wheel.</summary>
    internal const double CenterX = 108.080;
    internal const double WheelTop = 29.209;
    internal const double WheelBottom = 87.876;
    internal const double BodyTop = 14.230;
    internal const double BodyBottom = 286.847;
}
