using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using PadForge.Models2D;
using Xunit;

namespace PadForge.Tests
{
    /// <summary>
    /// The 2D colorway registry (generated by tools/gen_2d_colorways.py from
    /// the Gamepad-Asset-Pack templates). A colorway is one base render plus
    /// the rest-art sprites that differ from the default's; press-highlight
    /// art is shared. The registry's family keys write into the SAME per-pad
    /// appearance store the 3D picker uses (PadSetting.Model3DAppearances),
    /// so ids must match the 3D families' ids wherever the same physical
    /// colorway exists in both views.
    /// </summary>
    public class Controller2DColorwayTests
    {
        private static readonly string[] Folders =
            { "DualSense", "DUALSENSEEDGE", "DS4", "XBOXSERIES", "XBOXONE", "XBOX360" };

        private static string RepoRoot([CallerFilePath] string me = null)
            => Path.GetFullPath(Path.Combine(Path.GetDirectoryName(me), ".."));

        [Fact]
        public void EveryColorwayFolder_HasASet()
        {
            foreach (var folder in Folders)
            {
                var (famKey, set) = Controller2DColorways.For(folder);
                Assert.False(string.IsNullOrEmpty(famKey), folder);
                Assert.NotNull(set);
                Assert.True(set.Length >= 2, $"{folder} ships fewer than 2 colorways");
            }
        }

        [Fact]
        public void FoldersWithoutColorways_ReturnNull()
        {
            foreach (var folder in new[] { "SWITCHPRO", "SWITCH2PRO", "STEAMDECK", "MOUSE", "nope" })
            {
                var (famKey, set) = Controller2DColorways.For(folder);
                Assert.Null(famKey);
                Assert.Null(set);
            }
        }

        /// <summary>Entry 0 is the default and must be the stock files: its
        /// base is the layout's own BasePath file and it overrides nothing,
        /// so a pad with no stored appearance renders exactly what shipped
        /// before colorways existed.</summary>
        [Fact]
        public void DefaultEntry_IsTheStockArt()
        {
            var basePathByFolder = new Dictionary<string, string>
            {
                ["DualSense"] = DualSenseLayout.BasePath,
                ["DUALSENSEEDGE"] = DualSenseEdgeLayout.BasePath,
                ["DS4"] = DS4Layout.BasePath,
                ["XBOXSERIES"] = XboxSeriesXLayout.BasePath,
                ["XBOXONE"] = XboxOneSLayout.BasePath,
                ["XBOX360"] = Xbox360Layout.BasePath,
            };
            foreach (var folder in Folders)
            {
                var (_, set) = Controller2DColorways.For(folder);
                Assert.Equal(Path.GetFileName(basePathByFolder[folder]), set[0].BaseFile);
                Assert.Empty(set[0].Overrides);
            }
        }

        [Fact]
        public void Ids_AreUniquePerFolder_AndNamesNonEmpty()
        {
            foreach (var folder in Folders)
            {
                var (_, set) = Controller2DColorways.For(folder);
                Assert.Equal(set.Length, set.Select(c => c.Id).Distinct().Count());
                foreach (var c in set)
                {
                    Assert.False(string.IsNullOrWhiteSpace(c.Name), $"{folder}/{c.Id}");
                    Assert.False(string.IsNullOrWhiteSpace(c.BaseFile), $"{folder}/{c.Id}");
                }
            }
        }

        /// <summary>One selection drives both views, so every 2D id in a
        /// family that also has a 3D appearance list must BE a 3D id (or a
        /// deliberate 2D-only extension for DualSense/DS4). The Series set
        /// maps fully onto the 3D ids; a drifted casing here would make the
        /// 3D picker's choice invisible to the 2D view.</summary>
        [Fact]
        public void XboxSeriesIds_AreASubsetOfThe3DAppearanceIds()
        {
            var (_, set) = Controller2DColorways.For("XBOXSERIES");
            foreach (var c in set)
                Assert.Contains(c.Id, Models3D.ControllerModelXboxSeries.AppearanceIds);
        }

        [Fact]
        public void SharedPlayStationIds_MatchThe3DCasing()
        {
            var ds3d = Models3D.ControllerModelDualSense.AppearanceIds;
            var (_, ds) = Controller2DColorways.For("DualSense");
            foreach (var c in ds)
                if (c.Id is "White" or "Midnight" or "CosmicRed" or "NovaPink")
                    Assert.Contains(c.Id, ds3d);

            var ds43d = Models3D.ControllerModelDS4.AppearanceIds;
            var (_, d4) = Controller2DColorways.For("DS4");
            foreach (var c in d4)
                if (c.Id is "JetBlack" or "MagmaRed")
                    Assert.Contains(c.Id, ds43d);
        }

        /// <summary>The Edge derives from the DualSense set: same ids in the
        /// same order (its bases are the DualSense bases re-rendered with
        /// the gutter tiles), under its own family key so an Edge pad keeps
        /// its own selection.</summary>
        [Fact]
        public void EdgeSet_MirrorsTheDualSenseIds()
        {
            var (dsKey, ds) = Controller2DColorways.For("DualSense");
            var (edgeKey, edge) = Controller2DColorways.For("DUALSENSEEDGE");
            Assert.Equal("DualSense", dsKey);
            Assert.Equal("DualSenseEdge", edgeKey);
            Assert.Equal(ds.Select(c => c.Id), edge.Select(c => c.Id));
        }

        /// <summary>Every base and override file the registry references
        /// exists in the folder's 2DModels directory, and every override key
        /// is a file the folder's layout actually renders at rest (a
        /// TriggerBase or StickRing ImageFile).</summary>
        [Fact]
        public void EveryReferencedFile_ExistsAndTargetsRestArt()
        {
            var restByFolder = new Dictionary<string, HashSet<string>>
            {
                ["DualSense"] = RestFiles(DualSenseLayout.Overlays),
                ["DUALSENSEEDGE"] = RestFiles(DualSenseEdgeLayout.Overlays),
                ["DS4"] = RestFiles(DS4Layout.Overlays),
                ["XBOXSERIES"] = RestFiles(XboxSeriesXLayout.Overlays),
                ["XBOXONE"] = RestFiles(XboxOneSLayout.Overlays),
                ["XBOX360"] = RestFiles(Xbox360Layout.Overlays),
            };
            string models = Path.Combine(RepoRoot(), "PadForge.App", "2DModels");
            Assert.True(Directory.Exists(models), models);

            foreach (var folder in Folders)
            {
                var (_, set) = Controller2DColorways.For(folder);
                string dir = Path.Combine(models, folder);
                foreach (var c in set)
                {
                    Assert.True(File.Exists(Path.Combine(dir, c.BaseFile)),
                        $"{folder}/{c.Id}: missing base {c.BaseFile}");
                    foreach (var (orig, variant) in c.Overrides)
                    {
                        Assert.Contains(orig, restByFolder[folder]);
                        Assert.True(File.Exists(Path.Combine(dir, variant)),
                            $"{folder}/{c.Id}: missing sprite {variant}");
                    }
                }
            }
        }

        private static HashSet<string> RestFiles(OverlayElement[] overlays)
            => overlays
                .Where(o => o.ElementType is OverlayElementType.TriggerBase
                            or OverlayElementType.StickRing)
                .Select(o => o.ImageFile)
                .ToHashSet();
    }
}
