"""Derive per-control region geometry from the vendored Zergatul mouse SVG.

The art is authored as outline line-work: 18 stroke paths that draw the shell
and its seams, with no per-control shapes. The regions those seams ENCLOSE are
the controls, so they are recovered by rasterising the outline and flood-filling
the closed areas, then traced back to polygons in the SVG's own coordinate space.

Emits a C# source file of path-mini-language strings.
"""
import re, cairosvg, cv2, numpy as np, os, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "cand/zergatul-inputoverlay.svg"
OUT = sys.argv[2] if len(sys.argv) > 2 else "MouseArt.g.cs"

svg = open(SRC, encoding="utf-8").read()
vb = re.search(r'viewBox="([\d.\-\s]+)"', svg).group(1).split()
VW, VH = float(vb[2]), float(vb[3])

RW = 1200                                   # raster width for region recovery
cairosvg.svg2png(url=SRC, write_to="_z.png", output_width=RW, background_color="#000000")
g = cv2.imread("_z.png", cv2.IMREAD_GRAYSCALE)
RH = g.shape[0]
S = VW / RW                                 # raster px -> SVG units

ink = (g > 60).astype(np.uint8)
ink = cv2.morphologyEx(ink, cv2.MORPH_CLOSE, np.ones((3, 3), np.uint8))
n, lab, stats, cent = cv2.connectedComponentsWithStats((1 - ink).astype(np.uint8), 4)

regs = []
for i in range(1, n):
    x, y, w, h, a = stats[i]
    if a < RW * RH * 0.0006:                       # noise
        continue
    if x <= 1 and y <= 1 and w > RW * 0.9:         # the page outside the shell
        continue
    regs.append(dict(i=i, x=x, y=y, w=w, h=h, a=a, cx=cent[i][0], cy=cent[i][1]))
regs.sort(key=lambda r: -r["a"])
print(f"raster {RW}x{RH}, {len(regs)} enclosed regions")

def take(pred, many=False):
    hits = [r for r in regs if not r.get("used") and pred(r)]
    hits.sort(key=lambda r: -r["a"])
    if not hits:
        return [] if many else None
    if many:
        for h in hits:
            h["used"] = True
        return hits
    hits[0]["used"] = True
    return hits[0]

palm = take(lambda r: True)
lmb  = take(lambda r: r["cx"] < RW * .45 and r["cy"] < RH * .45 and r["a"] > RW * RH * .02)
rmb  = take(lambda r: r["cx"] > RW * .55 and r["cy"] < RH * .45 and r["a"] > RW * RH * .02)
whl  = take(lambda r: abs(r["cx"] - RW / 2) < RW * .10 and r["cy"] < RH * .45)
ridges = take(lambda r: abs(r["cx"] - RW / 2) < RW * .10 and r["cy"] < RH * .40, many=True)
sides  = take(lambda r: r["cx"] < RW * .22, many=True)
sides.sort(key=lambda r: r["cy"])
vents  = take(lambda r: True, many=True)

named = {}
if palm: named["Palm"] = palm
if lmb:  named["Lmb"] = lmb
if rmb:  named["Rmb"] = rmb
if whl:  named["WheelWell"] = whl
for k, r in enumerate(ridges): named[f"WheelRidge{k}"] = r
for k, r in enumerate(sides[:2]): named[["SideUpper", "SideLower"][k]] = r
for k, r in enumerate(vents): named[f"Vent{k}"] = r

def trace(reg):
    m = (lab == reg["i"]).astype(np.uint8) * 255
    cs, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    c = max(cs, key=cv2.contourArea)
    eps = 0.0015 * cv2.arcLength(c, True)
    p = cv2.approxPolyDP(c, eps, True).reshape(-1, 2)
    pts = [f"{x*S:.2f},{y*S:.2f}" for x, y in p]
    return "M " + " L ".join(pts) + " Z", len(p)

lines = [
    "// AUTO-GENERATED by tools/gen_mouse_art.py -- do not edit manually.",
    "//",
    "// Geometry derived from Zergatul.Obs.InputOverlay's mouse.svg.",
    "// Copyright (c) 2021 Igor Budzhak. Licensed under the MIT License.",
    "// https://github.com/Zergatul/Zergatul.Obs.InputOverlay",
    "//",
    "// The upstream art is outline line-work with no per-control shapes, so the",
    "// filled regions below were recovered by flood-filling the areas its seams",
    "// enclose and tracing them back into the SVG's own coordinate space.",
    "namespace PadForge.Views;",
    "",
    "internal static class MouseArt",
    "{",
    f"    internal const double W = {VW:.4f};",
    f"    internal const double H = {VH:.4f};",
    "",
]
vent_names = []
for name, reg in named.items():
    d, npts = trace(reg)
    lines.append(f"    /// <summary>{npts}-point region, area {reg['a']} raster px.</summary>")
    lines.append(f'    internal const string {name} = "{d}";')
    lines.append("")
    if name.startswith("Vent"):
        vent_names.append(name)

lines.append("    /// <summary>Decorative shell cutouts. Never lit, never routed.</summary>")
lines.append("    internal static readonly string[] Vents = { " + ", ".join(vent_names) + " };")
lines.append("")

def plain(m):
    # WPF's path mini-language does not reliably accept exponent notation,
    # which Inkscape emits for near-zero deltas. Expand it.
    return ("%.6f" % float(m.group(0))).rstrip("0").rstrip(".") or "0"

outline = [re.sub(r'-?\d*\.?\d+[eE][-+]?\d+', plain, d)
           for d in re.findall(r'<path[^>]*\sd="([^"]+)"', svg)]
lines.append("    /// <summary>The shell line-work, drawn over the filled regions.</summary>")
lines.append("    internal static readonly string[] Outline =")
lines.append("    {")
for d in outline:
    lines.append('        "' + " ".join(d.split()) + '",')
lines.append("    };")
lines.append("}")
open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")

print(f"emitted {OUT}: {len(named)} regions, {len(outline)} outline paths")
for k, r in named.items():
    print(f"   {k:<14} area={r['a']:<8} center=({r['cx']*S:.1f},{r['cy']*S:.1f})")
