"""Open the Steam Deck's stick wells and drop a dark socket into each.

The shell caps both wells with a disc of large flat triangles at
y = -3.58, the same plane the base bulb's back sits on, so the stick
stood on solid plastic and there was no opening under it. A ray cast
down either stick axis hits that disc and then nothing until the inside
of the back wall 22 mm later. Vertex radius alone does not find the
disc: the triangle over the left axis spans 17 mm and has every corner
outside the well.

So: cut the disc, and put a cup behind it. The bulb is 7.61 mm in radius
against an 8.79 mm well, so 1.2 mm of the cup shows at rest and a 2.7 mm
crescent opens at full deflection.

Both halves are idempotent. Rerunning cuts nothing and says so.
"""
import math
import os

RIM_R = 8.788          # the well rim in MainBody.obj, measured
RIM_Y = -3.575         # the floor plane it caps; -Y is out of the face
WALL_R = RIM_R - 0.08  # just inside the plastic, no z-fighting
FLOOR_Y = 12.0         # short of the shell's back wall at 18.8
SEG = 64
CENTERS = ((-102.83, 34.50), (102.83, 34.50))

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "PadForge.App", "3DModels", "SteamDeck")


def cup(cx, cz):
    v, vn, f = [], [], []

    def add(p, n):
        v.append(p)
        vn.append(n)
        return len(v)

    front, back = [], []
    for i in range(SEG):
        a = 2.0 * math.pi * i / SEG
        dx, dz = math.cos(a), math.sin(a)
        # Wall normals point at the axis: the wall we can see is the far
        # one, and its inner face is what the camera looks at.
        n = (-dx, 0.0, -dz)
        front.append(add((cx + WALL_R * dx, RIM_Y, cz + WALL_R * dz), n))
        back.append(add((cx + WALL_R * dx, FLOOR_Y, cz + WALL_R * dz), n))

    for i in range(SEG):
        j = (i + 1) % SEG
        f.append((front[i], back[i], back[j]))
        f.append((front[i], back[j], front[j]))

    # Floor, facing out of the controller's face.
    center = add((cx, FLOOR_Y, cz), (0.0, -1.0, 0.0))
    disc = [add((cx + WALL_R * math.cos(2.0 * math.pi * i / SEG), FLOOR_Y,
                 cz + WALL_R * math.sin(2.0 * math.pi * i / SEG)), (0.0, -1.0, 0.0))
            for i in range(SEG)]
    for i in range(SEG):
        f.append((center, disc[i], disc[(i + 1) % SEG]))

    return v, vn, f


def write(path, v, vn, f):
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Generated by tools/steam_deck_stick_well.py\n")
        for p in v:
            fh.write("v %.5f %.5f %.5f\n" % (p[0], p[1], p[2]))
        for n in vn:
            fh.write("vn %.5f %.5f %.5f\n" % (n[0], n[1], n[2]))
        for t in f:
            fh.write("f %d//%d %d//%d %d//%d\n" % (t[0], t[0], t[1], t[1], t[2], t[2]))
    print("%s: %d verts, %d tris" % (os.path.basename(path), len(v), len(f)))


def open_the_shell():
    path = os.path.join(OUT, "MainBody.obj")
    lines = open(path, encoding="utf-8", errors="ignore").read().splitlines()

    verts = []
    for ln in lines:
        if ln.startswith("v "):
            verts.append([float(x) for x in ln.split()[1:4]])

    def is_floor(idx):
        pts = [verts[i] for i in idx]
        if any(abs(p[1] - RIM_Y) > 0.02 for p in pts):
            return False
        gx = sum(p[0] for p in pts) / 3.0
        gz = sum(p[2] for p in pts) / 3.0
        return any(math.hypot(gx - cx, gz - cz) < 10.0 for cx, cz in CENTERS)

    out, cut = [], 0
    for ln in lines:
        if ln.startswith("f "):
            idx = [int(tok.split("/")[0]) - 1 for tok in ln.split()[1:]]
            if len(idx) >= 3 and is_floor(idx[:3]):
                cut += 1
                continue
        out.append(ln)

    if cut:
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(out) + "\n")
    print("MainBody.obj: %d well-floor triangles removed" % cut)


for cx, cz in CENTERS:
    name = "LeftStickWell.obj" if cx < 0 else "RightStickWell.obj"
    v, vn, f = cup(cx, cz)
    write(os.path.join(OUT, name), v, vn, f)
open_the_shell()
